spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default: http://localhost:8761/eureka/

